import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import scss from './../../styles/Login.module.scss';

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Login </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={scss.Login}>
        <h1> Login </h1>
        <div>
          <div>
            <div>
              <input type="text" placeholder='Username'/>
              <input type="password" placeholder='Email Address'/>
            </div>
          </div>
          <div>
            <div>
              <div>
                <Link href={"/home"}> 
                  <button>
                    Login
                  </button>
                </Link>
                <p>
                  <Link href={"/signup"}> Don&apos;t have an account? Join us now!</Link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Login
