import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../../component/footer';
import Nav from '../../component/navbar';

const Create: NextPage = () => {
  return (
    <>
      <Head>
        <title> Create Your Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav num={1}></Nav>

      <Footer></Footer>
    </>
  )
}

export default Create
