import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import scss from '../../styles/SignUp.module.scss';

const SignUp: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={scss.SignUp}>
        <h1> Sign Up </h1>
        <div>
          <div>
            <div>
              <input type="text" placeholder='Username'/>
              <input type="password" placeholder='Email Address'/>
            </div>
          </div>
          <div>
            <div>
              <div>
                <Link href={"/home"}> 
                  <button>
                    Sign Up
                  </button>
                </Link>
                <p>
                  <Link href={"/login"}> Have an account? Login now!</Link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default SignUp