import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../../component/navbar';
import Footer from '../../component/footer';
import scss from '../../styles/profile.module.scss';

const Setting: NextPage = () => {

  
  
    return ( <>
      <div>
        
        <Head>
        <title> Setting </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav num={5}></Nav>
        
        <Footer></Footer>
      </div>
      </> );
  }
  
  export default Setting