import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../../component/navbar';
import Footer from '../../component/footer';
import scss from '../../styles/profile.module.scss';
import Trending from '../../component/trending';
import Image from 'next/image';
const fakeData:{id:number; title:string;content:string;comments:number;likes:number}[] =  [
  {
    id: 1,
    title: "This is the first article",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!",
    comments: 10,
    likes: 59,
  },
  {
    id: 2,
    title: "This is the second article",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!",
    comments: 10,
    likes: 59,
  },
  {
    id: 3,
    title: "This is the third article",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!",
    comments: 10,
    likes: 59,
  },
  {
    id: 4,
    title: "This is the fourth article",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!",
    comments: 10,
    likes: 59,
  },
  {
    id: 5,
    title: "This is the fifth article",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!",
    comments: 10,
    likes: 59,
  },
];
const Profile: NextPage = () => {

  
  
  return ( <>
    <div>
      
      <Head>
      <title> Profile </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav num={3}></Nav>
      <div> 
      <section className={scss.profile}> 
      <div>
      <span>
            <Image src="/zikunw.jpg" alt="User Profile" className={scss.round} width={240} height={240} ></Image>        </span>
        <div className={scss.profileName}>Zikun Wang</div>
        <div className={scss.profileDes}> Hi I am a computer science student. 
        I like UI/UX design and stuff.<br></br> This is just filler text. Do not read too carefully.
              <br></br><br></br> Joined August 13 2022 </div>

      </div>
       <div className={scss.profileAns}>His answers:</div>
      </section>
      <section> 
        <div className={scss.profileEnd}> 
        ~This is the end of the Page~ 
        <br></br>
        ~There is nothing down here~
        </div>
      </section>
      </div>
      <Footer></Footer>
    </div>
    </> );
}

export default Profile

