import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../../component/navbar';
import Footer from '../../component/footer';
import scss from '../../styles/profile.module.scss';
import Image from 'next/image';
import Answer from '../../component/answer';

const fakeAnswer = [
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
  {
    username: "CoolGuy123",
    likes: 12,
    date: "2022-7-30 6:00PM",
    content: `Hi, there answer and answer.
    I can provide useful weblink: www.youtube.com`,
  },
]

const Profile: NextPage = () => {
  
  return ( <>
    <div>
      
      <Head>
      <title> Profile </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav num={3}></Nav>
      <div> 
      <section className={scss.profile}> 
      <div>
      <span>
            <Image src="/zikunw.jpg" alt="User Profile" className={scss.round} width={240} height={240} ></Image>        </span>
        <div className={scss.profileName}>Zikun Wang</div>
        <div className={scss.profileDes}> Hi I am a computer science student. 
        I like UI/UX design and stuff.<br></br> This is just filler text. Do not read too carefully.
              <br></br><br></br> Joined August 13 2022 </div>

      </div>
       <div className={scss.profileAns}>His answers:</div>
       <div className={scss.ans}>
        {fakeAnswer.map((answer, i) => 
            <Answer answer={answer} key={i} />
          )}
       </div>
      </section>
      <section> 
        <div className={scss.profileEnd}> 
        ~This is the end of the Page~ 
        <br></br>
        ~There is nothing down here~
        </div>
      </section>
      </div>

      
      <Footer></Footer>
    </div>
    </> );
}

export default Profile

