import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import scss from '../../styles/about.module.scss';

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title> About </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={scss.about}>

      </section>
    </div>
  )
}

export default About
