import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../../component/navbar';
import Footer from '../../component/footer';
import scss from '../../styles/about.module.scss';

const About: NextPage = () => {

  return (
    <div>
      <Head>
        <title> About </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav num={2}></Nav>

      <section className={scss.about}>
        <h1> About Us</h1>
        <h3> 
        Our website is open to anyone who is curious to learn. Everyone should be able to learn something new when they come into our website 
        and explore new possbility on different fields. The goal of our website is to resolve the education gap that exist in the United States 
        by allowing everyone to access our website that will contain many useful information on different fields.
        </h3>

      </section>

      <Footer></Footer>
    </div>
  )
}

export default About
