import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Nav from '../component/navbar';
import Footer from '../component/footer';
import Post from './post/[ID]';
import styles from '../styles/Welcome.module.scss';

const fakeData =  [
  {
    id: 1,
    title: "a",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!"
  },
  {
    id: 2,
    title: "b",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!"
  },
  {
    id: 3,
    title: "c",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!"
  },
  {
    id: 4,
    title: "d",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!"
  },
  {
    id: 5,
    title: "e",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi quo, commodi tempora quam eveniet nihil. Ad commodi, eum deleniti, reiciendis at dolorem et earum blanditiis incidunt nihil impedit iure ea!"
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Hello! </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav num={1}></Nav>

      {fakeData.map(data => 
        <h2 key={data.id.toString()}> <Link href={"/post/ID"} as={`/post/${data.id}`}> a</Link></h2>  
      )}
      <Footer></Footer>
    </div>
  )
}

export default Home
